### ISSUE TITLE
Crash paging exactly 1000 rows

### ISSUE THREAD

**Issue by david-allison-1** [david-allison-1/Anki-Android-Backend#28]
https://github.com/ankidroid/Anki-Android/issues/8055

**Comment by david-allison-1** [comment]
Hmm... different error running via unit tests

```
net.ankiweb.rsdroid.BackendFatalError: called `Option::unwrap()` on a `None` value
at net.ankiweb.rsdroid.RustBackendImpl.validateResult(RustBackendImpl.java:35)
at net.ankiweb.rsdroid.BackendV1Impl.getPage(BackendV1Impl.java:284)
at net.ankiweb.rsdroid.BackendMutex.getPage(BackendMutex.java:145)
at net.ankiweb.rsdroid.database.Session.getPage(Session.java:90)
at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.getNextPage(StreamingProtobufSQLiteCursor.java:66)
at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.moveToNext(StreamingProtobufSQLiteCursor.java:97)
at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursorTest.iterateAllRows(StreamingProtobufSQLiteCursorTest.java:69)
at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursorTest.testPaging(StreamingProtobufSQLiteCursorTest.java:56)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
```

**Comment by david-allison-1** [comment]
Fixed in https://github.com/david-allison-1/Anki-Android-Backend/commit/7c5037079bb31f1c80b55a995bd06b5a2fc0381d
