### ISSUE TITLE
Include Protobuf libraries 

### ISSUE THREAD

**Issue by david-allison-1** [david-allison-1/Anki-Android-Backend#29]
If not imported by dependencies, leads to:
```
	at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/InvalidProtocolBufferException
	at net.ankiweb.rsdroid.BackendFactory.getBackend(BackendFactory.java:40)
	at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.createRustSupportSQLiteDatabase(RustSupportSQLiteOpenHelper.java:90)
	at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.getWritableDatabase(RustSupportSQLiteOpenHelper.java:72)
	at com.ichi2.libanki.DB.<init>(DB.java:83)
	at com.ichi2.libanki.backend.RustDroidBackend.openCollectionDatabase(RustDroidBackend.java:39)
	at com.ichi2.libanki.Storage.Collection(Storage.java:76)
	at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:129)
	at com.ichi2.anki.RobolectricTest.getCol(RobolectricTest.java:240)
	at com.ichi2.async.CollectionTaskCheckDatabaseTest.lockDatabase(CollectionTaskCheckDatabaseTest.java:45)
	at com.ichi2.async.CollectionTaskCheckDatabaseTest.checkDatabaseWithLockedCollectionReturnsLocked(CollectionTaskCheckDatabaseTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.InvalidProtocolBufferException
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:163)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:129)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:115)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:115)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 28 more


```

**Comment by mikehardy** [comment]
@david-allison I'm not sure this is still valid? We've got a dependency entry for protobuf (technically protobuf-lite if I understand correctly) in the build.gradle files and I think that is good enough?

**Comment by david-allison** [comment]
I'll close as stale, it's not worth the effort to check if things are working

Assumed resolved
